#!/bin/sh

preselection='pt_1>50&&pt_2>40&&'\
'isoTight_1>0.5&&isoTight_2>0.5&&'\
'abs(eta_1)<2.1&&abs(eta_2)<2.1&&'\
'againstMuonTight3_1>0&&againstMuonTight3_2>0&&'\
'againstElectronVLooseMVA6_1>0&&againstElectronVLooseMVA6_2>0&&'\
'npv>0&&diLeptons==0&&tightMuons==0&&tightElectrons==0&&extraelec_veto==0&&extramuon_veto==0'

qcdselection='pt_1>50&&pt_2>40&&'\
'abs(eta_1)<2.1&&abs(eta_2)<2.1&&'\
'npv>0&&diLeptons==0&&tightMuons==0&&tightElectrons==0&&'\
'againstMuonTight3_1>0&&againstMuonTight3_2>0&&'\
'againstElectronVLooseMVA6_1>0&&againstElectronVLooseMVA6_2>0&&'\
'((isoMed_1>0.5&&isoTight_1<0.5&&isoTight_2>0.5)||(isoMed_2>0.5&&isoTight_2<0.5&&isoTight_1>0.5))'

#preselection='pt_1>40&&pt_2>40&&abs(eta_1)<2.1&&abs(eta_2)<2.1&&npv>0&&diLeptons==0&&isoTight_1>0.5&&isoTight_2>0.5&&tightMuons==0&&tightElectrons==0&&againstMuonTight3_2>0&&againstElectronVLooseMVA6_2>0&&againstMuonTight3_1>0&&againstElectronVLooseMVA6_1>0'
bselection='btag>=1'
antibselection='nbtag==0'
wselection='mt_1>70'
signalselection='pt_1>-10'
#qcdselection='pt_1>40&&pt_2>40&&abs(eta_1)<2.1&&abs(eta_2)<2.1&&npv>0&&diLeptons==0&&((isoMed_1>0.5&&isoTight_1<0.5&&isoTight_2>0.5)||(isoMed_2>0.5&&isoTight_2<0.5&&isoTight_1>0.5))&&tightMuons==0&&tightElectrons==0&&againstMuonTight3_2>0&&againstElectronVLooseMVA6_2>0&&againstMuonTight3_1>0&&againstElectronVLooseMVA6_1>0'
#qcdselection='pt_1>40&&pt_2>40&&abs(eta_1)<2.1&&abs(eta_2)<2.1&&npv>0&&diLeptons==0&&(isoTight_1<0.5&&isoTight_2<0.5)&&tightMuons==0&&tightElectrons==0&&againstMuonTight3_2>0&&againstElectronVLooseMVA6_2>0&&againstMuonTight3_1>0&&againstElectronVLooseMVA6_1>0'
trigselection='pt_1>24' #only for MC
trigselectiondata='HLT_Any>0&&run<276812' #only for Data
relaxedSelection='pt_1>40&&pt_2>40&&npv>0&&diLeptons==0&&((isoLoose_1>0.5&&isoTight_1<0.5&&isoTight_2>0.5)||(isoLoose_2>0.5&&isoTight_2<0.5&&isoTight_1>0.5))&&tightMuons==0&&tightElectrons==0&&againstMuonTight3_2>0&&againstElectronVLooseMVA6_2>0'
luminosity=12600 #pb
direc='/data/ojalvo/ztt_weighted27Corr/'
direcdata='/data/ojalvo/ztt_weighted27Corr/tauDATA.root'

zttScale=1.
topWeight=1.0
zWeight=1.0
qcdfactor=1.0
topSF=1.
bins=30
tauID=0.95
outputDir='diTauPlots'

mkdir $outputDir

binning='binningLowStat=20.,30.,40.,45.,50.,55.,60.,65.,70.,75.,80.,85.,90.,95.,100.,110.,120.,130.,150. binningHighStat=0.,20.,40.,60.,80.,100.,120.,140.,160.,180.,200.,250.,300.,350.' 

#signalselection='mJJ>100&&fullPt>100&&njets==2&&jdeta>3.5';
signalselection='pt_1>10'

MakeDataCardHThTh_2016 channel='diTau'  folder='tt_inclusive'  dataFile=$direcdata qcdFile=$direcdata zttFile=$direc'ZJETS.root' zllFile=$direc'ZJETS.root' wFile=$direc'WJETS.root' vvFile=$direc'DiBoson.root' topFile=$direc'TT.root' preselection=$preselection  wselection=$wselection  relaxedSelection=$relaxedSelection trigSelection=$trigselection trigSelectionData=$trigselectiondata  signalselection=$signalselection   qcdselection=$qcdselection luminosityErr=0.045 qcdfactor=$qcdfactor qcdfactorErr=0.02 vvErr=0.3   zttScale=$zttScale zttScaleErr=0.033    wFactorErr=0.06    zjfterr=0.1  zlfterr=0.24   topErr=0.075  topSF=$topSF  tauID=$tauID tauIDErr=0.06  dir=$direc''  bID=1.0  bIDErr=0.10  bMisID=1.0  bMisIDErr=0.17    bitmask=1,0,0,0  weight='__WEIGHT__*GENWEIGHT*puweight*__CORR__' Zweight='__ZWEIGHT__' luminosity=$luminosity  variable='eta_1' bins=20 min=-4 max=4 outputFile=$outputDir'/tauTau_eta1.root'  

MakeDataCardHThTh_2016 channel='diTau'  folder='tt_inclusive'  dataFile=$direcdata qcdFile=$direcdata zttFile=$direc'ZJETS.root' zllFile=$direc'ZJETS.root' wFile=$direc'WJETS.root' vvFile=$direc'DiBoson.root' topFile=$direc'TT.root' preselection=$preselection  wselection=$wselection  relaxedSelection=$relaxedSelection trigSelection=$trigselection trigSelectionData=$trigselectiondata  signalselection=$signalselection   qcdselection=$qcdselection luminosityErr=0.045 qcdfactor=$qcdfactor qcdfactorErr=0.02 vvErr=0.3   zttScale=$zttScale zttScaleErr=0.033    wFactorErr=0.06    zjfterr=0.1  zlfterr=0.24   topErr=0.075  topSF=$topSF  tauID=$tauID tauIDErr=0.06  dir=$direc''  bID=1.0  bIDErr=0.10  bMisID=1.0  bMisIDErr=0.17    bitmask=1,0,0,0  weight='__WEIGHT__*GENWEIGHT*puweight*__CORR__'  Zweight='__ZWEIGHT__'  luminosity=$luminosity  variable='m_vis' bins=20 min=0 max=350 outputFile=$outputDir'/tauTau_mvis.root'  

